// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: message/protobuf/address.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_message_protobuf_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_address_proto_rawDescGZIP(), []int{0}
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressInfo) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *AddressInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AddressInfo) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *AddressInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AddressInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddressInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_message_protobuf_address_proto protoreflect.FileDescriptor

const file_message_protobuf_address_proto_rawDesc = "" +
	"\n" +
	"\x1emessage/protobuf/address.proto\x12\rspitha.events\"\xcf\x01\n" +
	"\vAddressInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x05 \x01(\tR\x03zip\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitudeB\x12Z\x10message/protobufb\x06proto3"

var (
	file_message_protobuf_address_proto_rawDescOnce sync.Once
	file_message_protobuf_address_proto_rawDescData []byte
)

func file_message_protobuf_address_proto_rawDescGZIP() []byte {
	file_message_protobuf_address_proto_rawDescOnce.Do(func() {
		file_message_protobuf_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_protobuf_address_proto_rawDesc), len(file_message_protobuf_address_proto_rawDesc)))
	})
	return file_message_protobuf_address_proto_rawDescData
}

var file_message_protobuf_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_protobuf_address_proto_goTypes = []any{
	(*AddressInfo)(nil), // 0: spitha.events.AddressInfo
}
var file_message_protobuf_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_protobuf_address_proto_init() }
func file_message_protobuf_address_proto_init() {
	if File_message_protobuf_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_protobuf_address_proto_rawDesc), len(file_message_protobuf_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_protobuf_address_proto_goTypes,
		DependencyIndexes: file_message_protobuf_address_proto_depIdxs,
		MessageInfos:      file_message_protobuf_address_proto_msgTypes,
	}.Build()
	File_message_protobuf_address_proto = out.File
	file_message_protobuf_address_proto_goTypes = nil
	file_message_protobuf_address_proto_depIdxs = nil
}
