// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: message/protobuf/car.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Fuel          string                 `protobuf:"bytes,2,opt,name=fuel,proto3" json:"fuel,omitempty"`
	Transmission  string                 `protobuf:"bytes,3,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Year          int64                  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarInfo) Reset() {
	*x = CarInfo{}
	mi := &file_message_protobuf_car_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarInfo) ProtoMessage() {}

func (x *CarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_car_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarInfo.ProtoReflect.Descriptor instead.
func (*CarInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_car_proto_rawDescGZIP(), []int{0}
}

func (x *CarInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CarInfo) GetFuel() string {
	if x != nil {
		return x.Fuel
	}
	return ""
}

func (x *CarInfo) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *CarInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CarInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CarInfo) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

var File_message_protobuf_car_proto protoreflect.FileDescriptor

const file_message_protobuf_car_proto_rawDesc = "" +
	"\n" +
	"\x1amessage/protobuf/car.proto\x12\rspitha.events\"\x95\x01\n" +
	"\aCarInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04fuel\x18\x02 \x01(\tR\x04fuel\x12\"\n" +
	"\ftransmission\x18\x03 \x01(\tR\ftransmission\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x06 \x01(\x03R\x04yearB\x12Z\x10message/protobufb\x06proto3"

var (
	file_message_protobuf_car_proto_rawDescOnce sync.Once
	file_message_protobuf_car_proto_rawDescData []byte
)

func file_message_protobuf_car_proto_rawDescGZIP() []byte {
	file_message_protobuf_car_proto_rawDescOnce.Do(func() {
		file_message_protobuf_car_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_protobuf_car_proto_rawDesc), len(file_message_protobuf_car_proto_rawDesc)))
	})
	return file_message_protobuf_car_proto_rawDescData
}

var file_message_protobuf_car_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_protobuf_car_proto_goTypes = []any{
	(*CarInfo)(nil), // 0: spitha.events.CarInfo
}
var file_message_protobuf_car_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_protobuf_car_proto_init() }
func file_message_protobuf_car_proto_init() {
	if File_message_protobuf_car_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_protobuf_car_proto_rawDesc), len(file_message_protobuf_car_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_protobuf_car_proto_goTypes,
		DependencyIndexes: file_message_protobuf_car_proto_depIdxs,
		MessageInfos:      file_message_protobuf_car_proto_msgTypes,
	}.Build()
	File_message_protobuf_car_proto = out.File
	file_message_protobuf_car_proto_goTypes = nil
	file_message_protobuf_car_proto_depIdxs = nil
}
