// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: message/protobuf/job.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Descriptor_   string                 `protobuf:"bytes,3,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_message_protobuf_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobInfo) GetDescriptor_() string {
	if x != nil {
		return x.Descriptor_
	}
	return ""
}

func (x *JobInfo) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_message_protobuf_job_proto protoreflect.FileDescriptor

const file_message_protobuf_job_proto_rawDesc = "" +
	"\n" +
	"\x1amessage/protobuf/job.proto\x12\rspitha.events\"o\n" +
	"\aJobInfo\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x03 \x01(\tR\n" +
	"descriptor\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05levelB\x12Z\x10message/protobufb\x06proto3"

var (
	file_message_protobuf_job_proto_rawDescOnce sync.Once
	file_message_protobuf_job_proto_rawDescData []byte
)

func file_message_protobuf_job_proto_rawDescGZIP() []byte {
	file_message_protobuf_job_proto_rawDescOnce.Do(func() {
		file_message_protobuf_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_protobuf_job_proto_rawDesc), len(file_message_protobuf_job_proto_rawDesc)))
	})
	return file_message_protobuf_job_proto_rawDescData
}

var file_message_protobuf_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_protobuf_job_proto_goTypes = []any{
	(*JobInfo)(nil), // 0: spitha.events.JobInfo
}
var file_message_protobuf_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_protobuf_job_proto_init() }
func file_message_protobuf_job_proto_init() {
	if File_message_protobuf_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_protobuf_job_proto_rawDesc), len(file_message_protobuf_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_protobuf_job_proto_goTypes,
		DependencyIndexes: file_message_protobuf_job_proto_depIdxs,
		MessageInfos:      file_message_protobuf_job_proto_msgTypes,
	}.Build()
	File_message_protobuf_job_proto = out.File
	file_message_protobuf_job_proto_goTypes = nil
	file_message_protobuf_job_proto_depIdxs = nil
}
