// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: message/protobuf/movie.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Genre         string                 `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieInfo) Reset() {
	*x = MovieInfo{}
	mi := &file_message_protobuf_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieInfo) ProtoMessage() {}

func (x *MovieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieInfo.ProtoReflect.Descriptor instead.
func (*MovieInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_movie_proto_rawDescGZIP(), []int{0}
}

func (x *MovieInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MovieInfo) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

var File_message_protobuf_movie_proto protoreflect.FileDescriptor

const file_message_protobuf_movie_proto_rawDesc = "" +
	"\n" +
	"\x1cmessage/protobuf/movie.proto\x12\rspitha.events\"5\n" +
	"\tMovieInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\tR\x05genreB\x12Z\x10message/protobufb\x06proto3"

var (
	file_message_protobuf_movie_proto_rawDescOnce sync.Once
	file_message_protobuf_movie_proto_rawDescData []byte
)

func file_message_protobuf_movie_proto_rawDescGZIP() []byte {
	file_message_protobuf_movie_proto_rawDescOnce.Do(func() {
		file_message_protobuf_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_protobuf_movie_proto_rawDesc), len(file_message_protobuf_movie_proto_rawDesc)))
	})
	return file_message_protobuf_movie_proto_rawDescData
}

var file_message_protobuf_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_protobuf_movie_proto_goTypes = []any{
	(*MovieInfo)(nil), // 0: spitha.events.MovieInfo
}
var file_message_protobuf_movie_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_protobuf_movie_proto_init() }
func file_message_protobuf_movie_proto_init() {
	if File_message_protobuf_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_protobuf_movie_proto_rawDesc), len(file_message_protobuf_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_protobuf_movie_proto_goTypes,
		DependencyIndexes: file_message_protobuf_movie_proto_depIdxs,
		MessageInfos:      file_message_protobuf_movie_proto_msgTypes,
	}.Build()
	File_message_protobuf_movie_proto = out.File
	file_message_protobuf_movie_proto_goTypes = nil
	file_message_protobuf_movie_proto_depIdxs = nil
}
