// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: message/protobuf/person.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- PersonInfo fields ---
	FirstName     string                     `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                     `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender        string                     `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Ssn           string                     `protobuf:"bytes,4,opt,name=ssn,proto3" json:"ssn,omitempty"`
	Hobby         string                     `protobuf:"bytes,5,opt,name=hobby,proto3" json:"hobby,omitempty"`
	Job           *PersonInfo_JobInfo        `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"` // nested 타입 사용
	Address       *PersonInfo_AddressInfo    `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Contact       *PersonInfo_ContactInfo    `protobuf:"bytes,8,opt,name=contact,proto3" json:"contact,omitempty"`
	CreditCard    *PersonInfo_CreditCardInfo `protobuf:"bytes,9,opt,name=credit_card,json=creditCard,proto3" json:"credit_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonInfo) Reset() {
	*x = PersonInfo{}
	mi := &file_message_protobuf_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfo) ProtoMessage() {}

func (x *PersonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfo.ProtoReflect.Descriptor instead.
func (*PersonInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_person_proto_rawDescGZIP(), []int{0}
}

func (x *PersonInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PersonInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *PersonInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PersonInfo) GetSsn() string {
	if x != nil {
		return x.Ssn
	}
	return ""
}

func (x *PersonInfo) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *PersonInfo) GetJob() *PersonInfo_JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *PersonInfo) GetAddress() *PersonInfo_AddressInfo {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PersonInfo) GetContact() *PersonInfo_ContactInfo {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *PersonInfo) GetCreditCard() *PersonInfo_CreditCardInfo {
	if x != nil {
		return x.CreditCard
	}
	return nil
}

// --- nested types ---
type PersonInfo_JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Descriptor_   string                 `protobuf:"bytes,3,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonInfo_JobInfo) Reset() {
	*x = PersonInfo_JobInfo{}
	mi := &file_message_protobuf_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonInfo_JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfo_JobInfo) ProtoMessage() {}

func (x *PersonInfo_JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfo_JobInfo.ProtoReflect.Descriptor instead.
func (*PersonInfo_JobInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_person_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PersonInfo_JobInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *PersonInfo_JobInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PersonInfo_JobInfo) GetDescriptor_() string {
	if x != nil {
		return x.Descriptor_
	}
	return ""
}

func (x *PersonInfo_JobInfo) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type PersonInfo_AddressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonInfo_AddressInfo) Reset() {
	*x = PersonInfo_AddressInfo{}
	mi := &file_message_protobuf_person_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonInfo_AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfo_AddressInfo) ProtoMessage() {}

func (x *PersonInfo_AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_person_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfo_AddressInfo.ProtoReflect.Descriptor instead.
func (*PersonInfo_AddressInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_person_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PersonInfo_AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PersonInfo_AddressInfo) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *PersonInfo_AddressInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PersonInfo_AddressInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PersonInfo_AddressInfo) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *PersonInfo_AddressInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PersonInfo_AddressInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PersonInfo_AddressInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PersonInfo_ContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonInfo_ContactInfo) Reset() {
	*x = PersonInfo_ContactInfo{}
	mi := &file_message_protobuf_person_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonInfo_ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfo_ContactInfo) ProtoMessage() {}

func (x *PersonInfo_ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_person_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfo_ContactInfo.ProtoReflect.Descriptor instead.
func (*PersonInfo_ContactInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_person_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PersonInfo_ContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonInfo_ContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PersonInfo_CreditCardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Exp           string                 `protobuf:"bytes,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Cvv           string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonInfo_CreditCardInfo) Reset() {
	*x = PersonInfo_CreditCardInfo{}
	mi := &file_message_protobuf_person_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonInfo_CreditCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfo_CreditCardInfo) ProtoMessage() {}

func (x *PersonInfo_CreditCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protobuf_person_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfo_CreditCardInfo.ProtoReflect.Descriptor instead.
func (*PersonInfo_CreditCardInfo) Descriptor() ([]byte, []int) {
	return file_message_protobuf_person_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PersonInfo_CreditCardInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PersonInfo_CreditCardInfo) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *PersonInfo_CreditCardInfo) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *PersonInfo_CreditCardInfo) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

var File_message_protobuf_person_proto protoreflect.FileDescriptor

const file_message_protobuf_person_proto_rawDesc = "" +
	"\n" +
	"\x1dmessage/protobuf/person.proto\x12\rspitha.events\"\xea\x06\n" +
	"\n" +
	"PersonInfo\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x10\n" +
	"\x03ssn\x18\x04 \x01(\tR\x03ssn\x12\x14\n" +
	"\x05hobby\x18\x05 \x01(\tR\x05hobby\x123\n" +
	"\x03job\x18\x06 \x01(\v2!.spitha.events.PersonInfo.JobInfoR\x03job\x12?\n" +
	"\aaddress\x18\a \x01(\v2%.spitha.events.PersonInfo.AddressInfoR\aaddress\x12?\n" +
	"\acontact\x18\b \x01(\v2%.spitha.events.PersonInfo.ContactInfoR\acontact\x12I\n" +
	"\vcredit_card\x18\t \x01(\v2(.spitha.events.PersonInfo.CreditCardInfoR\n" +
	"creditCard\x1ao\n" +
	"\aJobInfo\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x03 \x01(\tR\n" +
	"descriptor\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x1a\xcf\x01\n" +
	"\vAddressInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x05 \x01(\tR\x03zip\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x1a9\n" +
	"\vContactInfo\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x1a`\n" +
	"\x0eCreditCardInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\tR\x03exp\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvvB\x12Z\x10message/protobufb\x06proto3"

var (
	file_message_protobuf_person_proto_rawDescOnce sync.Once
	file_message_protobuf_person_proto_rawDescData []byte
)

func file_message_protobuf_person_proto_rawDescGZIP() []byte {
	file_message_protobuf_person_proto_rawDescOnce.Do(func() {
		file_message_protobuf_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_protobuf_person_proto_rawDesc), len(file_message_protobuf_person_proto_rawDesc)))
	})
	return file_message_protobuf_person_proto_rawDescData
}

var file_message_protobuf_person_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_protobuf_person_proto_goTypes = []any{
	(*PersonInfo)(nil),                // 0: spitha.events.PersonInfo
	(*PersonInfo_JobInfo)(nil),        // 1: spitha.events.PersonInfo.JobInfo
	(*PersonInfo_AddressInfo)(nil),    // 2: spitha.events.PersonInfo.AddressInfo
	(*PersonInfo_ContactInfo)(nil),    // 3: spitha.events.PersonInfo.ContactInfo
	(*PersonInfo_CreditCardInfo)(nil), // 4: spitha.events.PersonInfo.CreditCardInfo
}
var file_message_protobuf_person_proto_depIdxs = []int32{
	1, // 0: spitha.events.PersonInfo.job:type_name -> spitha.events.PersonInfo.JobInfo
	2, // 1: spitha.events.PersonInfo.address:type_name -> spitha.events.PersonInfo.AddressInfo
	3, // 2: spitha.events.PersonInfo.contact:type_name -> spitha.events.PersonInfo.ContactInfo
	4, // 3: spitha.events.PersonInfo.credit_card:type_name -> spitha.events.PersonInfo.CreditCardInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_protobuf_person_proto_init() }
func file_message_protobuf_person_proto_init() {
	if File_message_protobuf_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_protobuf_person_proto_rawDesc), len(file_message_protobuf_person_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_protobuf_person_proto_goTypes,
		DependencyIndexes: file_message_protobuf_person_proto_depIdxs,
		MessageInfos:      file_message_protobuf_person_proto_msgTypes,
	}.Build()
	File_message_protobuf_person_proto = out.File
	file_message_protobuf_person_proto_goTypes = nil
	file_message_protobuf_person_proto_depIdxs = nil
}
