## Kafka settings
bootstrap-server: localhost:9092

## Topic settings
topic: 
  name: datagen-spitha

## Limit Data Amount Per Sec 
datagen:
  go-routine: 1
  produce:
    mode: rate-per-second
    rate-per-second: 10
  message:
    mode: quickstart
    quickstart: user