## Kafka settings
bootstrap-server: localhost:9092
producer:
  compression-type: uncompressed
  client-id: clientId
  transactional-id: transactionId

## Topic settings
topic: 
  name: datagen-users
  partition: 6
  replica-factor: 2

# ## Datagen settings
datagen:
  go-routine: 1
  produce:
    mode: rate-per-second
    rate-per-second: 10
  message:
    mode: quickstart
    quickstart: user
