## Kafka settings
bootstrap-server: localhost:9093
producer:
  schema-registry:
    server:
      urls: localhost:8081
      username: admin
      password: sradmin
    subject: schema-registry-name
    type: avro
  compression-type: uncompressed
  client-id: test
  sasl:
    mechanism: SCRAM-SHA-512
    username: admin
    password: admin-secret


## Topic settings
topic: 
  name: schema-registry-topic

## Datagen settings
## Limit Data Amount Per Sec 
datagen:
  
  ### proudce type
  interval: 100
  # limit-data-amount-per-second : 10000000
  # rate-per-second: 5

  ### message type
  quickstart: user
  # message-bytes: 100
  # jitter: 0.5
  go-routine: 1
