## Kafka settings
bootstrap-server: {BOOTSTRAP_SERVER}
producer:
  sasl:
    mechanism: AWS_MSK_IAM
    aws-access-key-id: {AWS_ACCESS_KEY_ID}
    aws-secret-access-key: {AWS_SECRET_ACCESS_KEY}

## Topic settings
topic: 
  name: datagen-users-msk-iam
  partition: 3
  replica-factor: 1

## Datagen settings
datagen:
  quickstart: users
  go-routine: 1
  rate-per-second: 10

datagen:
  go-routine: 1
  produce:
    mode: rate-per-second
    rate-per-second: 10
  message:
    mode: quickstart
    quickstart: user