## Kafka settings
bootstrap-server: {BOOTSTRAP_SERVER}
producer:
  sasl:
    mechanism: SCRAM-SHA-512
    username: {USERNAME}
    password: {PASSWORD}

## Topic settings
topic: 
  name: datagen-users-scram
  partition: 3
  replica-factor: 1

## Datagen settings
datagen:
  go-routine: 1
  produce:
    mode: rate-per-second
    rate-per-second: 10
  message:
    mode: quickstart
    quickstart: user