#!/bin/bash

set -e

## PRODUCER
export PRODUCER_MAX_MESSAGE_BYTES=100
export PRODUCER_LINGERS=0
export PRODUCER_COMPRESSION_TYPE=snappy

## SASL SCRAM
export PRODUCER_SASL_MECHANISM=SCRAM-SHA-512
export PRODUCER_SASL_USERNAME=admin
export PRODUCER_SASL_PASSWORD=admin-secret

## SASL OAUTHBEARER
export PRODUCER_SASL_MECHANISM=OAUTHBEARER
export PRODUCER_SASL_CLIENT_ID=test
export PRODUCER_SASL_CLIENT_SECRET=test2
export PRODUCER_SASL_TOKEN_ENDPOINT=test3

## SASL AWS_MSK_IAM
export PRODUCER_SASL_MECHANISM=AWS_MSK_IAM
export PRODUCER_SASL_AWS_ACCESS_KEY_ID=test1
export PRODUCER_SASL_AWS_SECRET_ACCESS_KEY=test2

## TLS
export PRODUCER_TLS_CAFILE=cafile
export PRODUCER_TLS_CERTFILE=certfile
export PRODUCER_TLS_KEYFILE=keyfile
export PRODUCER_TLS_SKIPVERIFY=skipverify

## TOPIC
export TOPIC_NAME=test
export TOPIC_PARTITION=6
export TOPIC_REPLICA_FACTOR=1

## DATAGEN
export DATAGEN_QUICKSTART=user
export DATAGEN_MESSAGE_BYTES=100
export DATAGEN_GO_ROUTINE=1
export DATAGEN_RATE_PER_SECOND=100
export DATAGEN_INTERVAL=100
export DATAGEN_LIMIT_DATA_AMOUNT_PER_SECOND=100000

./gomplate -f ./in/datagen.yaml.tmpl -o ./datagen.yaml
