#!/bin/bash

set -e
## BOOTSTRAP SERVER
export BOOTSTRAP__SERVER=localhost:9092

## PRODUCER
export PRODUCER_MAX__MESSAGE__BYTES=100
export PRODUCER_LINGERS=0
export PRODUCER_COMPRESSION__TYPE=snappy

## SASL SCRAM
export PRODUCER_SASL__MECHANISM=SCRAM-SHA-512
export PRODUCER_SASL__USERNAME=admin
export PRODUCER_SASL__PASSWORD=admin-secret

## SASL OAUTHBEARER
export PRODUCER_SASL__MECHANISM=OAUTHBEARER
export PRODUCER_SASL__CLIENT__ID=test
export PRODUCER_SASL__CLIENT__SECRET=test2
export PRODUCER_SASL__TOKEN__ENDPOINT=test3

## SASL AWS__MSK__IAM
export PRODUCER_SASL__MECHANISM=AWS_MSK_IAM
export PRODUCER_SASL__AWS__ACCESS__KEY__ID=test1
export PRODUCER_SASL__AWS__SECRET__ACCESS__KEY=test2

## TLS
export PRODUCER_TLS__CAFILE=cafile
export PRODUCER_TLS__CERTFILE=certfile
export PRODUCER_TLS__KEYFILE=keyfile
export PRODUCER_TLS__SKIPVERIFY=skipverify

## TOPIC
export TOPIC_NAME=test
export TOPIC_PARTITION=6
export TOPIC_REPLICA__FACTOR=1

## DATAGEN
export DATAGEN_QUICKSTART=user
export DATAGEN_MESSAGE__BYTES=100
export DATAGEN_GO__ROUTINE=1
export DATAGEN_RATE__PER__SECOND=100
export DATAGEN_INTERVAL=100
export DATAGEN_DATA_RATE_LIMIT_BPS=100000

# ./gomplate -f ./in/datagen.yaml.tmpl -o ./datagen.yaml

echo ${!DATAGEN*} ${!TOPIC*} ${!PRODUCER*} ${!BOOTSTRAP*} | ./gomplate -d config=stdin: -f ./in/datagen.yaml.tmpl -o ./datagen.yaml